### ISSUE TITLE
5.5.3 节 headless-service.yaml 勘误

### ISSUE THREAD

**Issue by acan107** [kubeguide/K8sDefinitiveGuide-V6-A-corrigendum#35]
## 书名

- [x] 《Kubernetes 权威指南》第6版 上册

## 问题所在页码

372-373

## 问题描述

例如，在下面的配置中有 2 个 Pod 和 1 个 Headless Service, 服务名（name）与 Pod
子域名被设置为相同的值 “mysubdomain”：
```
# headless-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysubdomain
spec:
  selector:
    app: webapp
  clusterIP: None
  ports:
  - port: 8080
```

**问题**：配置文件（headless-service.yaml）中的内容和文字中的描述不一致。该配置文件只有 1 个 Headless Service，并没有 2 个 Pod。

运行 `kubectl create -f headless-service.yaml` 文件后运行 `nslookup webapp-1.mysubdomain.default.svc.cluster.local` 命令无法得到与书中一致的输出。

个人认为上面的内容可改为

例如，在下面的配置中有 1 个 Headless Service, 服务名（name）与刚创建的 Pod
的子域名为相同的值 “mysubdomain”：
```
# headless-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: mysubdomain
spec:
  selector:
    app: webapp1
  clusterIP: None
  ports:
  - port: 8080
```

注意：标签选择器的值必须和 Pod 中的标签一致 （app: webapp1）
